import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { listWorkdirs, markWorkdirGenerated, getMachineId } from "../db/workdirs.js";
import type { Project, ProjectWorkdir } from "../types/index.js";

export interface GenerateResult {
  path: string;
  claude_md: string;
  agents_md: string;
  written: boolean; // false on dry-run
}

function buildWorkdirList(workdirs: ProjectWorkdir[], currentPath: string): string {
  return workdirs
    .map((w) => {
      const isCurrent = w.path === currentPath;
      const primary = w.is_primary ? " (primary)" : "";
      const current = isCurrent ? " ← you are here" : "";
      return `- \`${w.path}\` [${w.label}]${primary}${current}  *(machine: ${w.machine_id})*`;
    })
    .join("\n");
}

function claudeMdContent(project: Project, workdir: ProjectWorkdir, allWorkdirs: ProjectWorkdir[]): string {
  const otherDirs = allWorkdirs.filter((w) => w.path !== workdir.path);
  const otherSection = otherDirs.length
    ? `\n## Other Working Directories\n${buildWorkdirList(otherDirs, workdir.path)}\n`
    : "";

  const integrations = Object.keys(project.integrations).length
    ? `\n## Integrations\n${Object.entries(project.integrations)
        .filter(([, v]) => v)
        .map(([k, v]) => `- **${k}:** \`${v}\``)
        .join("\n")}\n`
    : "";

  const tags = project.tags.length ? `\n**Tags:** ${project.tags.join(", ")}` : "";

  return `# Project: ${project.name}

> ${project.description ?? `Working directory for project **${project.name}**`}
${tags}

## Working Directory

You are working in the **${workdir.label}** directory for this project:

\`\`\`
${workdir.path}
\`\`\`

**Write all code to this directory.** Do not write to other project directories unless explicitly instructed.

## Project Metadata

| Field | Value |
|-------|-------|
| ID | \`${project.id}\` |
| Slug | \`${project.slug}\` |
| Label | \`${workdir.label}\` |
| Machine | \`${workdir.machine_id}\` |
| Status | ${project.status} |
${project.git_remote ? `| Git Remote | ${project.git_remote} |` : ""}
${project.s3_bucket ? `| S3 Bucket | \`${project.s3_bucket}\` |` : ""}
${integrations}${otherSection}
## All Working Directories

${buildWorkdirList(allWorkdirs, workdir.path)}

## Instructions for AI Agents

1. **Write code in \`${workdir.path}\`** — this is your working directory for this session.
2. Use \`project sync ${project.slug}\` to push changes to S3.
3. Use \`project git ${project.slug} <args>\` to run git commands.
4. If you need to switch to a different workdir, call \`projects_open\` with the project ID.

---
*Generated by open-projects. Regenerate: \`project workdir generate ${project.slug}\`*
`.trimStart();
}

function agentsMdContent(project: Project, workdir: ProjectWorkdir, allWorkdirs: ProjectWorkdir[]): string {
  const otherDirs = allWorkdirs.filter((w) => w.path !== workdir.path);

  return `---
project_id: ${project.id}
project_slug: ${project.slug}
project_name: ${project.name}
working_directory: ${workdir.path}
label: ${workdir.label}
machine_id: ${workdir.machine_id}
is_primary: ${workdir.is_primary}
---

# ${project.name} — Agent Instructions

## Scope

This agent session is scoped to the **${workdir.label}** working directory:

\`\`\`
${workdir.path}
\`\`\`

**Only write files inside this directory** unless the user explicitly asks you to work elsewhere.
${otherDirs.length ? `\n## Other workdirs for this project\n\n${otherDirs.map((w) => `- \`${w.path}\` [${w.label}] on ${w.machine_id}`).join("\n")}\n` : ""}
## Quick Reference

\`\`\`bash
# Open this project
cd ${workdir.path}

# Sync to S3
project sync ${project.slug}

# Git operations
project git ${project.slug} status
project git ${project.slug} log --oneline -10
\`\`\`
${Object.keys(project.integrations).length ? `\n## Service IDs\n\n${Object.entries(project.integrations).filter(([, v]) => v).map(([k, v]) => `- **${k}:** \`${v}\``).join("\n")}\n` : ""}
---
*Generated by open-projects ${new Date().toISOString().slice(0, 10)}*
`.trimStart();
}

export function generateForWorkdir(
  project: Project,
  workdir: ProjectWorkdir,
  allWorkdirs: ProjectWorkdir[],
  options: { dryRun?: boolean; force?: boolean } = {},
): GenerateResult {
  const claudeMd = claudeMdContent(project, workdir, allWorkdirs);
  const agentsMd = agentsMdContent(project, workdir, allWorkdirs);

  const claudePath = join(workdir.path, "CLAUDE.md");
  const agentsPath = join(workdir.path, "AGENTS.md");

  let written = false;

  if (!options.dryRun && existsSync(workdir.path)) {
    // Merge with existing CLAUDE.md if present (append project section)
    if (existsSync(claudePath) && !options.force) {
      const existing = readFileSync(claudePath, "utf-8");
      // Only overwrite if it was generated by us or if forced
      if (existing.includes("Generated by open-projects")) {
        writeFileSync(claudePath, claudeMd, "utf-8");
      } else {
        // Append our section to existing CLAUDE.md
        const separator = "\n\n---\n\n<!-- open-projects -->\n";
        const marker = "<!-- open-projects -->";
        if (existing.includes(marker)) {
          // Replace the open-projects section
          const before = existing.slice(0, existing.indexOf(marker) - separator.length + 1);
          writeFileSync(claudePath, before + separator + claudeMd, "utf-8");
        } else {
          writeFileSync(claudePath, existing.trimEnd() + separator + claudeMd, "utf-8");
        }
      }
    } else {
      writeFileSync(claudePath, claudeMd, "utf-8");
    }

    writeFileSync(agentsPath, agentsMd, "utf-8");
    markWorkdirGenerated(project.id, workdir.path);
    written = true;
  }

  return { path: workdir.path, claude_md: claudeMd, agents_md: agentsMd, written };
}

export function generateAllWorkdirs(
  project: Project,
  options: { dryRun?: boolean; force?: boolean } = {},
): GenerateResult[] {
  const workdirs = listWorkdirs(project.id);
  return workdirs.map((w) => generateForWorkdir(project, w, workdirs, options));
}
