import chalk from "chalk";
import { resolve } from "node:path";
import { resolveProjectOrExit, type Command } from "./shared.js";
import { addWorkdir, listWorkdirs, removeWorkdir } from "../../../db/workdirs.js";
import { generateForWorkdir, generateAllWorkdirs } from "../../../lib/generate.js";

export function registerWorkdirCommands(cmd: Command) {
  const workdirCmd = cmd.command("workdir").description("Manage working directories for a project");

  workdirCmd
    .command("add <id-or-slug> <path>")
    .description("Add a working directory to a project")
    .option("--label <label>", "Label for this directory (e.g. frontend, backend)", "main")
    .option("--primary", "Set as the primary working directory")
    .option("--generate", "Generate CLAUDE.md + AGENTS.md immediately")
    .action((idOrSlug, path, opts) => {
      const project = resolveProjectOrExit(idOrSlug);
      const absPath = resolve(path);
      const workdir = addWorkdir({ project_id: project.id, path: absPath, label: opts.label, is_primary: opts.primary });
      console.log(chalk.green(`✓ Added workdir: ${workdir.label} → ${workdir.path}`));
      if (opts.generate) {
        const allDirs = listWorkdirs(project.id);
        const result = generateForWorkdir(project, workdir, allDirs);
        console.log(chalk.dim(`  CLAUDE.md → ${result.path}/CLAUDE.md`));
        console.log(chalk.dim(`  AGENTS.md → ${result.path}/AGENTS.md`));
      }
    });

  workdirCmd
    .command("list <id-or-slug>")
    .description("List all working directories for a project")
    .option("-j, --json", "Output raw JSON")
    .action((idOrSlug, opts?: { json?: boolean }) => {
      const project = resolveProjectOrExit(idOrSlug);
      const workdirs = listWorkdirs(project.id);
      if (opts?.json || process.env["PROJECTS_JSON"]) { console.log(JSON.stringify(workdirs, null, 2)); return; }
      if (!workdirs.length) { console.log(chalk.dim("No workdirs registered.")); return; }
      for (const w of workdirs) {
        const primary = w.is_primary ? chalk.cyan(" [primary]") : "";
        const gen = w.claude_md_generated ? chalk.dim(" ✓ CLAUDE.md") : "";
        console.log(`${chalk.bold(w.label)}${primary}  ${chalk.dim(w.path)}${gen}`);
        console.log(`  ${chalk.dim("machine:")} ${w.machine_id}`);
      }
    });

  workdirCmd
    .command("remove <id-or-slug> <path>")
    .description("Remove a working directory from a project")
    .action((idOrSlug, path) => {
      const project = resolveProjectOrExit(idOrSlug);
      removeWorkdir(project.id, resolve(path));
      console.log(chalk.yellow(`✓ Removed workdir: ${path}`));
    });

  workdirCmd
    .command("generate <id-or-slug>")
    .description("Generate CLAUDE.md + AGENTS.md in all working directories")
    .option("--path <path>", "Only generate for a specific workdir path")
    .option("--dry-run", "Show what would be generated without writing")
    .option("--force", "Overwrite existing CLAUDE.md even if not generated by open-projects")
    .action((idOrSlug, opts) => {
      const project = resolveProjectOrExit(idOrSlug);
      const allDirs = listWorkdirs(project.id);

      if (opts.path) {
        const absPath = resolve(opts.path);
        const workdir = allDirs.find((w) => w.path === absPath);
        if (!workdir) { console.error(chalk.red(`Workdir not found: ${absPath}`)); process.exit(1); }
        const result = generateForWorkdir(project, workdir, allDirs, { dryRun: opts.dryRun, force: opts.force });
        console.log(opts.dryRun ? chalk.dim("[dry-run]") : chalk.green("✓"), result.path);
      } else {
        const results = generateAllWorkdirs(project, { dryRun: opts.dryRun, force: opts.force });
        for (const r of results) {
          console.log(opts.dryRun ? chalk.dim("[dry-run]") : chalk.green("✓"), `${r.path}/CLAUDE.md + AGENTS.md`);
        }
        if (!opts.dryRun) console.log(chalk.green(`✓ Generated for ${results.length} workdir(s)`));
      }
    });
}
