import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  isHttpMode as harnessIsHttpMode,
  isStdioMode as harnessIsStdioMode,
  resolveMcpHttpPort as harnessResolveMcpHttpPort,
} from "@hasna/mcp-harness";
import {
  handleMcpHttpRequest as harnessHandleMcpHttpRequest,
  startBunHttpServer,
} from "@hasna/mcp-harness/bun";

/**
 * open-projects MCP transport/port boilerplate — thin shim over @hasna/mcp-harness.
 * Public API (options-object dialect) preserved; transport/port/health removed.
 * Generated by open-mcp/scripts/adopt-harness.ts.
 */

export const MCP_HTTP_HOST = "127.0.0.1";
export const DEFAULT_MCP_HTTP_PORT = 8871;

export function isHttpMode(args: readonly string[] = process.argv): boolean {
  return harnessIsHttpMode(args);
}
export function isStdioMode(args: readonly string[] = process.argv): boolean {
  return harnessIsStdioMode(args);
}
export function resolveMcpHttpPort(args: readonly string[] = process.argv): number {
  return harnessResolveMcpHttpPort({ argv: args, default: DEFAULT_MCP_HTTP_PORT });
}
export async function handleMcpRequest(
  req: Request,
  buildServer: () => McpServer,
): Promise<Response> {
  return harnessHandleMcpHttpRequest(req, buildServer);
}
export function startMcpHttpServer(options: {
  name: string;
  port: number;
  buildServer: () => McpServer;
}): { port: number; stop: () => void } {
  return startBunHttpServer(options.buildServer, {
    port: options.port,
    host: MCP_HTTP_HOST,
    serviceName: options.name,
  });
}
